name: "Increment the version code of your project and returns the inputs as outputs"
description: "This action will increment the version code directly in build.gradle . "
inputs:
  gradlePath:
    description: "Gradle path to override version"
    required: true
    default: "app/build.gradle"
  versionCode:
    description: "The new version code"
    required: false
  versionName:
    description: "The new version name"
    required: false
outputs:
  result: # id of output
    description: "Action Result"
  outputVersionName: # result of version name
    description: "Result of Version Name"
  outputVersionCode: # result of version code
    description: "Result of Version Code"
runs:
  using: "node12"
  main: "index.js"
branding:
  color: 'blue'
  icon: 'anchor'
